// Code generated by "esc -include=.*\.tmpl -o=tmpl.go -pkg=templates ./"; DO NOT EDIT.

package templates

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return fis[0:limit], nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// FS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func FS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// Dir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func Dir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// FSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func FSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// FSMustByte is the same as FSByte, but panics if name is not present.
func FSMustByte(useLocal bool, name string) []byte {
	b, err := FSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// FSString is the string version of FSByte.
func FSString(useLocal bool, name string) (string, error) {
	b, err := FSByte(useLocal, name)
	return string(b), err
}

// FSMustString is the string version of FSMustByte.
func FSMustString(useLocal bool, name string) string {
	return string(FSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/.tmpl.go.swp": {
		name:    ".tmpl.go.swp",
		local:   ".tmpl.go.swp",
		size:    1024,
		modtime: 1661508452,
		compressed: `
H4sIAAAAAAAC/0oyyEvMy1cw0zNhQAHl4gwM2YmV+cUMhEFaRlZ+XiphlSWpuQU5iSWpxfoluQU5eun5
DKNgFIyCgQSAAAAA//9NFFSEAAQAAA==
`,
	},

	"/astronaut1712/call.tmpl": {
		name:    "call.tmpl",
		local:   "astronaut1712/call.tmpl",
		size:    236,
		modtime: 1661507924,
		compressed: `
H4sIAAAAAAAC/0SOQcrCQAyF9/8pQuniF0oOIHiAbkRUdB2maQ20o2RGRYbcXabUzurBx5f3klLHvXiG
ytE4VmYpvSXeAI/sWF6smUgP/h4B23CK+nQxM/Zdjp8GaIYrxT1NbPafkpIfGGppoOYRtjvAAylNHFnD
Ul2LWQPrbRm7qsT8AOkQSvd8n+dmFc+fB2MbLqRCnTgzxOLOsVny7xsAAP//GjDYLOwAAAA=
`,
	},

	"/astronaut1712/function.tmpl": {
		name:    "function.tmpl",
		local:   "astronaut1712/function.tmpl",
		size:    2240,
		modtime: 1661507924,
		compressed: `
H4sIAAAAAAAC/6xVTW/bOBA9S79iok0Ca6FVsFcFPrRIUvTQpnCC5hgo0tAhKlMGScUwCP73YkhRtuKP
Gmgutjyc0Zs373FsTI2MC4SEdaLSvBWJtbEx/8E5g2IKubVxTEdgTP6ISn8vF2jtRMO/GpXmYp4/pmDi
iEpWXL9CPsMK+RtKa+PIhTmD/Kt60LKrtAsO0TuOTa18LLq6ghvfy6KtfsErSqQkgVhj7TKoTJZiju8q
qXRhjItRx67xPB9qUNQb3PBj63nr8SOI6PUSgbkIKJdMAzrW/3bvNOf1EvujUfvRaSQ+gsNz338xDUxO
p1CMxMj+kge1Rsb7UcpygRqlg3QzLuV8NOGt5nYrHKIL7Yx5C33cAACAQ1qVQh+DmqHqGq3CQJ9KoY+h
DMRmqDsp1K2UrZcoIqRbKeGlbZtREfXiP2Un7uhGkjadqEZ3MTPmvfBgzFj0XlD/lQ0Iw4OfK31ksPLU
Uy//AV8dchbFQ2K4l74ZGopLLqW1l8b0Dfj4z7Lp0FoTXnHAcZExud9GRc8l37HdO99F9vhO2Abb457A
8UlyPVAfuaqYwuXLWqPKP3eMoTSnANKSa/XYDDCAalwsm1IjJNKbLIFz5lTdnFRl0/jwIYA9Tos469W4
F816fA4opVdrH8g19IrBhPLOpiB4k9L3Kg/+7dXTuXsjmyTbr1qgUuUceyboCE/h4i2DUH7xlmQjdC6W
3cAdpcw2WOlG6rAsRvfRndHJQ/dCF0WBtdLRNQYbhdZWrdBcdNjT2medo17ZheQMas7cX2i1WOY3nLGJ
MV9atxao982SSK996tkUkqSf2yljc5zOWVD2W9dovmzo4gScIBMJUwpdwIVKMgeW7uVEK1fns05MEmIE
VakQ/vm/gMf7m/sCPtU10PxcmP6ek2x3AflN0a+oiSYR/7iQno+vImO9L5SxaRzZNLZxHJT6HQAA///9
NOmAwAgAAA==
`,
	},

	"/astronaut1712/header.tmpl": {
		name:    "header.tmpl",
		local:   "astronaut1712/header.tmpl",
		size:    173,
		modtime: 1661507924,
		compressed: `
H4sIAAAAAAAC/0TMMQ7CMAwF0N2niDLB0PQQTCyIK4TUuBU4jkqYrH93pFbAZvn//9wnvi+VQ5w5T7xG
gNzXXIVDOpkq1/4C3NMWcJ3CAFDL5ZGFg3u67idAtGiztYfDXzhvnx24ZGVgn/T5ywEUZenz+5aK6Shm
8uRRbCjaxqIt0vFX/AQAAP//+VGmmq0AAAA=
`,
	},

	"/astronaut1712/inline.tmpl": {
		name:    "inline.tmpl",
		local:   "astronaut1712/inline.tmpl",
		size:    49,
		modtime: 1661507924,
		compressed: `
H4sIAAAAAAAC/6quTklNy8xLVVDKzMvJzEtVqq1VqK4uSc0tyEksSVVQSk7MyVFS0AOLpual1NYCAgAA
//+q60H/MQAAAA==
`,
	},

	"/astronaut1712/inputs.tmpl": {
		name:    "inputs.tmpl",
		local:   "astronaut1712/inputs.tmpl",
		size:    152,
		modtime: 1661507924,
		compressed: `
H4sIAAAAAAAC/0yNMQoCQQxFrxKWLSUHEDyAneAJIptZptgomWz1yd1lRoupEh7/vw9sWqopLdU+Z7Ql
E1gLXW/E/a2F7B3Ez/MV2qJlRrDJoRcC1LZ/Zi388GpxH5IOXWzXwcXl0FD/dcX3xsCgfWLyzOcbAAD/
/468z9qYAAAA
`,
	},

	"/astronaut1712/message.tmpl": {
		name:    "message.tmpl",
		local:   "astronaut1712/message.tmpl",
		size:    201,
		modtime: 1661507924,
		compressed: `
H4sIAAAAAAAC/zyN4WqDQBCE//sUiyi0oPsAhT5A/xRpS/9f4mgW9GLuTkNY9t2DB/HXDDPDN6o9BvGg
ckaMbkRJrVmhKgP5ayL+XU8JMUWz+sakCt+bqd4lXYh/cIZsCHvCf48F/O+mFWZ8DPnbzTB7y0Tugvj0
5Zd1B6oG50dQJQ1VmOjjk7hzwc1ICLmXgSoxa16/9XZws7wXqi1l+wwAAP//kC65UskAAAA=
`,
	},

	"/astronaut1712/results.tmpl": {
		name:    "results.tmpl",
		local:   "astronaut1712/results.tmpl",
		size:    168,
		modtime: 1661507924,
		compressed: `
H4sIAAAAAAAC/1yNTQrCQAyFr/Iosyw9gOBS3HsDoRkJlAy8ma5C7i6pRcFVfr4vee6rVDXBROn7NvoU
AXc+7SUoOqPIhssVy+ODI9y1omjEDHexNTf3NrBkc85a82DstH4jG1MW8uQ4hMbv0385A3/uUd8BAAD/
/7BPz2GoAAAA
`,
	},

	"/dotlou/call.tmpl": {
		name:    "call.tmpl",
		local:   "dotlou/call.tmpl",
		size:    236,
		modtime: 1661507260,
		compressed: `
H4sIAAAAAAAC/0yO0YrCQAxFfyWUPuxCyQcs7Af0ZVlU9DlMUw20o6RRkZB/lynV+nThzrlz4t5xL5mh
SjQMVYT7XewEuOHEcmMtjfSQzwbYTlvTa7IIS+jOuSuvLxIwYm3xj0aO+HJXykeGWhqoeYCfX8B/UhrZ
WKfl91oiGnhvV99BxcoNn755XWQziLvHhbGd9qRCnaQIxJWd43vJZwAAAP//s98A7uwAAAA=
`,
	},

	"/dotlou/function.tmpl": {
		name:    "function.tmpl",
		local:   "dotlou/function.tmpl",
		size:    1590,
		modtime: 1661507260,
		compressed: `
H4sIAAAAAAAC/5RTT2/bPgw925+CCIoi/iFV7wF6+A3Lhl2aIQ3WwzAMqk1nxhw5lehtgcDvPuiP/yRx
hi2XWJRIPvK9Z22BZaUQZmWrcqoaNWNOrb2DmxKWDyCY09RdgbVii4Ye5R6Z5wT/ERqq1E5sM7Bp4lJ+
VvQNxAZzrH6gZk4TH65KEB/ME+k2Jx/so+8qrAsTYgkdDwilj4Dxj13d+FpLtcOzhMRaf3YgPbzjAeOV
S0FVxFPfswuNvkefbiDjhv78ZdRfyT06PJXaxcyJMbuJpCqGWc/gxtHCX4+oNgPmruTlQFfA94t0zHyU
Wu6RUJshJ65t6jqx1of+rdmo4AZNW1Pf7Fkquqg1hXWD1GplVlo3cXn464A5YbHSGtCFTzPZ0XB/D9v1
2/US/i8KcExBLg0akTp2y0aDtVUJ80aDeGpfApVz1ZCj41F+xyLLmOHrAih3FFvri8d5wnObQvx1UPtK
zCQ2rZpTLpweFuAscW4CiJjhbtjjlFaumOJCAR6mZ/d4QP9YaubbCD2uWXySdYvMtitxxSuJtSJ4dwmU
i6BCMXLQYigwOCeZsNPFIfabEFg35rOuqJ/+RHjLB7h9ORIa8aYtS9T2bxpGowV616o+jiWVQd+ecH+o
JSHMdNDqDG5Kr9DhJpd1HcLXWk0INtBy3pnZqTfQNtUgEucKaHxtK41i9drKek5OlWLkgoUrlP1p2RcG
BJiqOdhyAda+b/xnNmXyM7kDZ6dy5pTTtJvgdwAAAP//izfJkDYGAAA=
`,
	},

	"/dotlou/header.tmpl": {
		name:    "header.tmpl",
		local:   "dotlou/header.tmpl",
		size:    142,
		modtime: 1661507260,
		compressed: `
H4sIAAAAAAAC/0TMMQ7CMAyF4d2nsDrBQC7BxIK4gkUebYXiViGb9e6OlAi6/bL1voiM1+rQaYFl1ImU
iGo+Q9N1KwXePmRE6g941gspuz3fNkMj0mMkKbKWfatNT4dw65cB3K2AHJO2/DhSzv/6BgAA///GzMM9
jgAAAA==
`,
	},

	"/dotlou/inline.tmpl": {
		name:    "inline.tmpl",
		local:   "dotlou/inline.tmpl",
		size:    49,
		modtime: 1661507260,
		compressed: `
H4sIAAAAAAAC/6quTklNy8xLVVDKzMvJzEtVqq1VqK4uSc0tyEksSVVQSk7MyVFS0AOLpual1NYCAgAA
//+q60H/MQAAAA==
`,
	},

	"/dotlou/inputs.tmpl": {
		name:    "inputs.tmpl",
		local:   "dotlou/inputs.tmpl",
		size:    147,
		modtime: 1661507260,
		compressed: `
H4sIAAAAAAAC/0yMQQoCMRAEvzIse5Q8QPAB3gRfEN2O5LCjTGZPzfxdEj3k1E3RXeSGUhWyVP0c3pYI
ci1yvkjqtRbRt0u6Hw9H8xbhz6R5x0lI6PbfrCXdrKpfh6RDy/rC4NnyDof9vuQA3T4p5vgGAAD//ykp
rjaTAAAA
`,
	},

	"/dotlou/message.tmpl": {
		name:    "message.tmpl",
		local:   "dotlou/message.tmpl",
		size:    201,
		modtime: 1661507260,
		compressed: `
H4sIAAAAAAAC/zyN4WqDQBCE//sUiyi0oPsAhT5A/xRpS/9f4mgW9GLuTkNY9t2DB/HXDDPDN6o9BvGg
ckaMbkRJrVmhKgP5ayL+XU8JMUWz+sakCt+bqd4lXYh/cIZsCHvCf48F/O+mFWZ8DPnbzTB7y0Tugvj0
5Zd1B6oG50dQJQ1VmOjjk7hzwc1ICLmXgSoxa16/9XZws7wXqi1l+wwAAP//kC65UskAAAA=
`,
	},

	"/dotlou/results.tmpl": {
		name:    "results.tmpl",
		local:   "dotlou/results.tmpl",
		size:    168,
		modtime: 1661507260,
		compressed: `
H4sIAAAAAAAC/1yNTQrCQAyFr/Iosyw9gOBS3HsDoRkJlAy8ma5C7i6pRcFVfr4vee6rVDXBROn7NvoU
AXc+7SUoOqPIhssVy+ODI9y1omjEDHexNTf3NrBkc85a82DstH4jG1MW8uQ4hMbv0385A3/uUd8BAAD/
/7BPz2GoAAAA
`,
	},

	"/testify/call.tmpl": {
		name:    "call.tmpl",
		local:   "testify/call.tmpl",
		size:    241,
		modtime: 1661507246,
		compressed: `
H4sIAAAAAAAC/0SOQWrDQAxFryKMFy0YHaDQA3hTSlvatRjLrsCeFo2SEITuHsY4mdWHP2/el/vEs2SG
LtG6dhHuF7FfwA9OLGfW2sgM+c8Ax/JpekoWYYbunKf6eicBI1qLb7RxxJO7Ul4Yehmg5xVeXgHfSWlj
Yy2HvZeIAR5/296PitUbzJB0KU2/K+riTuPX9Z9xLN+kQpOkCMTG7vF85C0AAP//ZQi8iPEAAAA=
`,
	},

	"/testify/function.tmpl": {
		name:    "function.tmpl",
		local:   "testify/function.tmpl",
		size:    2798,
		modtime: 1661507246,
		compressed: `
H4sIAAAAAAAC/5xWUW/cNgx+tn8FYQTFebiq7yn60GHtkJemSIL1oRgG9UzfjPl0N4necBD43wdRlu3z
2VnTPOQsyiQ/8qM+y/sK68YgFNo5tNQcTQGvmXMiNVg2tAXvmxrUvWnPD0idNe6DtUfL7D3h4dRqQih2
um0LUMGIrUNmtNZ7NBVz7v1raGo4WtiYI4F67L4ROnIlqM+2MXRnTh05SQ0AsIX6QOrxFLbqTTHNckDn
9B4lURGAjVuNBJGdUjKiqSTksGLO83wsGv/udFswx1LVh7CUSv8HJ3PdF5bqm0Y9uH0Rdr4nDmzhB6p7
JnndmZ3Q2Df9pobbd8Enz8MWeK+e0NEnfUDmDcFPAVZj9uqpBJ9nweXfhv4E9YA7bP5By5xnWU+funOP
ZLsdiXGwfmywrVy0ZXQ+IdRiAScvh7j921abPc4cMu9lHUAKvPMJ+62RtbAacibT5Hn2GFCFMj9rqw9I
aCWZQNN2fwFsAuvaQxKK6QrdJONlfuE5NN17wRFaXTEf9OmrI9uY/e8xezolX8d1CNCDCq5xdMS/ZDb6
gBAjJOKzNb5SE7SpRtJmfe85ij9DawVSX3gKec3MCgvP9D7LpPHh34LPhIAHdF1LLuX5og091/sh5aUu
ScIkYJDOd9h7n6wfO7Ob8Rha/+YNPN3/cn8L76sKApew0w6dEprro41SuDna8VD3RN25T/ovrMpS0E6o
D8wltv/oudsCURySyHrsQAznJ2WlHBe1hta2LbbMMQjR28uRSNSnFy+gBI/w+9Z7UUjxIvXQmc0qbCLV
LyP4oCXX6rGIcHjelJcgh5O9NsQrsnM1mtJGGbvzCeVlbZlfDSoZ7b/ptkNmn0KsqFHmvYrqeAtEKh4P
NdGo7Rhg1KZsQbCuFn2+BYlJZX6xDQ3VX0jP7Tt49e1M6NTPXV2j9d+TsB+DOJ7zj3d5bb83KF0qYUA2
fn9sPJgF3NQy4PMPfzCvoZifTpj9TaNNbiKrIdf0YqmVsPA3zRcvAZIr3HSI1Kg64Qs8cKAeRXzDGE8+
2G4ffcuRj6ihy3kF3k291PUVn5find4Y2sZgfHUF8xrIZ2p4KZ5fjxTvLC8DMByt1RGfSyQwA5cwvfhl
nHO4HUWX/wIAAP//vN7yje4KAAA=
`,
	},

	"/testify/header.tmpl": {
		name:    "header.tmpl",
		local:   "testify/header.tmpl",
		size:    142,
		modtime: 1661507246,
		compressed: `
H4sIAAAAAAAC/0TMMQ7CMAyF4d2nsDrBQC7BxIK4gkUebYXiViGb9e6OlAi6/bL1voiM1+rQaYFl1ImU
iGo+Q9N1KwXePmRE6g941gspuz3fNkMj0mMkKbKWfatNT4dw65cB3K2AHJO2/DhSzv/6BgAA///GzMM9
jgAAAA==
`,
	},

	"/testify/inline.tmpl": {
		name:    "inline.tmpl",
		local:   "testify/inline.tmpl",
		size:    49,
		modtime: 1661507246,
		compressed: `
H4sIAAAAAAAC/6quTklNy8xLVVDKzMvJzEtVqq1VqK4uSc0tyEksSVVQSk7MyVFS0AOLpual1NYCAgAA
//+q60H/MQAAAA==
`,
	},

	"/testify/inputs.tmpl": {
		name:    "inputs.tmpl",
		local:   "testify/inputs.tmpl",
		size:    177,
		modtime: 1661507246,
		compressed: `
H4sIAAAAAAAC/0yNMaoDMQxE+38KsWz58QECOUCaEMgJFCwvLqwESVsJ3T1YpHAlzWN4416pdSbYOn9O
0y3CfW9wuUKZb2/Ab4PyPF9GarqyOw6qEWbFnbhGMA76h1/I3t7KQzrbLeUTCvJByVFwkJFoKlAOLe5J
5/TiWc/fNwAA//94+RPrsQAAAA==
`,
	},

	"/testify/message.tmpl": {
		name:    "message.tmpl",
		local:   "testify/message.tmpl",
		size:    201,
		modtime: 1661507246,
		compressed: `
H4sIAAAAAAAC/zyN4WqDQBCE//sUiyi0oPsAhT5A/xRpS/9f4mgW9GLuTkNY9t2DB/HXDDPDN6o9BvGg
ckaMbkRJrVmhKgP5ayL+XU8JMUWz+sakCt+bqd4lXYh/cIZsCHvCf48F/O+mFWZ8DPnbzTB7y0Tugvj0
5Zd1B6oG50dQJQ1VmOjjk7hzwc1ICLmXgSoxa16/9XZws7wXqi1l+wwAAP//kC65UskAAAA=
`,
	},

	"/testify/results.tmpl": {
		name:    "results.tmpl",
		local:   "testify/results.tmpl",
		size:    168,
		modtime: 1661507246,
		compressed: `
H4sIAAAAAAAC/1yNTQrCQAyFr/Iosyw9gOBS3HsDoRkJlAy8ma5C7i6pRcFVfr4vee6rVDXBROn7NvoU
AXc+7SUoOqPIhssVy+ODI9y1omjEDHexNTf3NrBkc85a82DstH4jG1MW8uQ4hMbv0385A3/uUd8BAAD/
/7BPz2GoAAAA
`,
	},

	"/": {
		name:  "/",
		local: `./`,
		isDir: true,
	},

	"/astronaut1712": {
		name:  "astronaut1712",
		local: `astronaut1712`,
		isDir: true,
	},

	"/dotlou": {
		name:  "dotlou",
		local: `dotlou`,
		isDir: true,
	},

	"/testify": {
		name:  "testify",
		local: `testify`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	"./": {
		_escData["/.tmpl.go.swp"],
	},

	"astronaut1712": {
		_escData["/astronaut1712/call.tmpl"],
		_escData["/astronaut1712/function.tmpl"],
		_escData["/astronaut1712/header.tmpl"],
		_escData["/astronaut1712/inline.tmpl"],
		_escData["/astronaut1712/inputs.tmpl"],
		_escData["/astronaut1712/message.tmpl"],
		_escData["/astronaut1712/results.tmpl"],
	},

	"dotlou": {
		_escData["/dotlou/call.tmpl"],
		_escData["/dotlou/function.tmpl"],
		_escData["/dotlou/header.tmpl"],
		_escData["/dotlou/inline.tmpl"],
		_escData["/dotlou/inputs.tmpl"],
		_escData["/dotlou/message.tmpl"],
		_escData["/dotlou/results.tmpl"],
	},

	"testify": {
		_escData["/testify/call.tmpl"],
		_escData["/testify/function.tmpl"],
		_escData["/testify/header.tmpl"],
		_escData["/testify/inline.tmpl"],
		_escData["/testify/inputs.tmpl"],
		_escData["/testify/message.tmpl"],
		_escData["/testify/results.tmpl"],
	},
}
